### ISSUE TITLE
Negative alignment scores (?)

### ISSUE THREAD

**Issue by Ahhgust** [lh3/ksw2#1]
Hi Heng!
I've been dabbling a bit with the sourcecode you've provided here, and I believe I have come across a bug (or more likely, a user error :) ). Using the ksw2-test program:
 ./ksw2-test -t gg   target.fa.gz query.fa.gz

where the fasta files are:
augustw@penny:~/src/KSW2$ zcat query.fa.gz
>query
ATACTGTGGAACTTCTTAGCCTCCTTAATAGTGTGAGCCCATTTTCATAATAAATCCCCTCTCATCTATCTGACTGTCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCCTATTGGTTCTGTTTCTCTGGA

augustw@penny:~/src/KSW2$ zcat target.fa.gz
>target
TCCAGAGAAACAGAACCAATAGGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGACAGTCAGAT

The program returns:
target  query   -53     0       -1      -1      1I11M5I2M1I4M2I5M5I1M12I5M12I2M3I2M9I45M1I1M3I1M1I6M8I

Which gives an alignment score of -53. I believe that the defaults for the program are alignments under the unit edit distance (though perhaps I am reading that incorrectly), which should make negative alignment scores a little hard to pull off. The actual relationship between the reads is pretty obvious, but I figured that you might want to know about this.
Thanks!
-August Woerner

**Comment by lh3** [comment]
`-53` is the global alignment score, which can be negative. The cigar corresponds to the global alignment. `0` is the extension score. It suggests the alignment can't be extended.

> The actual relationship between the reads is pretty obvious

Your query and target are on different strands. ksw2-test is only a test program. You have to do reverse complement by yourself.

By the way, your example is interesting in that it is sensitive to the scoring in use. The default breaks the long insertion into pieces. `ksw2-test -O3` (you need to pull the latest change) collapses them into one insertion. A proper scoring is something I would like to explore, too.

**Comment by Ahhgust** [comment]
Doh! My apologies-- I forgot which objective function was which (not framed as a shortest path problem... I guess I'm getting rusty)! 
Thanks again for the help.
-August
