### ISSUE TITLE
Difference in reported Alignment Score for `extz` and `extz2_sse`

### ISSUE THREAD

**Issue by k3yavi** [lh3/ksw2#11]
Hi @lh3 ,
We (+ @rob-p ) were trying to test some corner cases we found while comparing different alignment methods. Specifically for ksw2, an important case we are still trying to understand is as follows. 

If you consider the two implementation of ksw2 DP i.e. `extz` and `extz2_sse` and test it on a toy example with `N` in its sequence then the reported alignment scores does not seem to match. For example:
```
╰─$ ./ksw2-test -t extz -g AGATTA AGANTA
first   second  10      10      5       5       6M
╰─$ ./ksw2-test -t extz2_sse AGATTA AGANTA
first   second  8       8       5       5       6M
```

As expected `extz` is giving a score of 10 since there was 1 mismatch but `extz2_sse` seems to give score lesser than expected and it keep decreasing by 2 as the number of `N` in the sequence increase. We were wondering, if the two modes were intentionally implemented like this or it's a bug ? We can be missing some important information in the understanding of the two modes too. 

Thanks in advance for your help and writing this awesome tool.

**Comment by lh3** [comment]
Sorry for the late response. The culprit is [ksw2_extz2_sse.c:68](https://github.com/lh3/ksw2/blob/master/ksw2_extz2_sse.c#L68). When matching to "N" gets a score 0, the SSE version uses gap extension as the penalty. This was added later to minimap2 and sync'd back to ksw2.

**Comment by k3yavi** [comment]
Thanks for the tip, explicitly changing the gap extension penalty seems to fix it for the toy example.
```
╰─$ ./ksw2-test -t extz -g AGATTA AGANTA
first   second  10      10      5       5       6M
╰─$ ./ksw2-test -t extz2_sse -g AGATTA AGANTA
first   second  8       8       5       5       6M
╰─$ ./ksw2-test -t extz2_sse -g AGATTA AGANTA -E 0
first   second  10      10      5       5       6M
```

But for our use case of performing alignment of short reads, setting extension penalty to 0 might not be the right thing and we'd prefer to use `extz2_sse` since it has its own performance benefits. 
Is it possible to have a feature request for this? or If you can please suggest the required changes to be made in the code for setting gap extension to behave like `extz` in case of `N`, we'd really appreciate that.

**Comment by k3yavi** [comment]
Hopefully changing the line you recommended to `sc_N_ = _mm_set1_epi8(mat[m*m-1])`, would be the only change needed and the right thing to do ?

**Comment by k3yavi** [comment]
Thanks @lh3 for the prompt response.
