### ISSUE TITLE
Mechanics of calling ksw_extz

### ISSUE THREAD

**Issue by standage** [lh3/ksw2#2]
Great tool. Thanks for sharing!

I'd like to drop ksw2 into an existing project, but I am having trouble getting the call to `ksw_extz` to work correctly. I have copied and pasted quite a bit from `cli.c` into [`align.cpp`](https://github.com/standage/ksw2-align/blob/e83506df4b2045ad2c2090d9c05a617132dafd45/align.cpp). For now I've hard-coded many parameters and I'm just trying to get the alignment to work. I'm testing the function call with a very simple [main method](https://github.com/standage/ksw2-align/blob/e83506df4b2045ad2c2090d9c05a617132dafd45/main.cpp).

Do you have any suggestions for what I might be doing wrong? Thanks!

**Comment by standage** [comment]
> Do you have any suggestions for what I might be doing wrong? Thanks!

I should clarify that when I try to run the main method, I get an empty CIGAR string back.

**Comment by lh3** [comment]
You need to manually convert A/C/G/T/N to 0/1/2/3/4. Have you done that part elsewhere? The code snip does not show.

**Comment by standage** [comment]
Ah, I have not. I'll try that and report back.

**Comment by lh3** [comment]
Also, bandwidth can't be -1. You can give the longer length as bandwidth. Probably I should make all functions accept -1 as bandwidth.

**Comment by standage** [comment]
Unless I'm reading `cli.c` incorrectly, or unless you handle it elsewhere, it looks like bandwidth is set to -1 unless the user explicitly overrides it. That was my inspiration, but I'm happy to fix it! :-)

**Comment by lh3** [comment]
There was a line in `global_aln()` that re-assign the bandwidth. I have just pushed a change to make all functions accept negative bandwidth. That line in `global_aln()` has also been removed.

**Comment by standage** [comment]
Great! Converting the sequences from `char *` to `uint8_t *` and updating the `ksw2` files to handle `bandwidth = -1` seems to have worked. Many thanks!

**Comment by lh3** [comment]
I have added a code example to README.
