### ISSUE TITLE
Optimal alignment out of bandwidth

### ISSUE THREAD

**Issue by Dmitry-Antipov** [lh3/ksw2#20]
In case when optimal alignment is out of bandwidth, cigar string can be nonsense (insertions followed by deletions, 1I1D15M1I1D15M1I1D15M).

Seems that such cases can be detected by nonzero flag _zdropped_ in _ksw_extz_t_ , but see no confirmation in comments/readme - am I right?

**Comment by lh3** [comment]
What is the scoring in use?

**Comment by Dmitry-Antipov** [comment]
I've tried different scoring schemes. Last one was 1, -5, 5, 2 (match, mismatch, gap_open, gap_extend). 

But after increasing bandwidth cigar became normal, so I do not think scoring matters here.

**Comment by lh3** [comment]
mismatch should be a positive number

**Comment by Dmitry-Antipov** [comment]
but it is negative in example from readme:

void align(const char *tseq, const char *qseq, int sc_mch, int sc_mis, int gapo, int gape)
align("ATAGCTAGCTAGCAT", "AGCTAcCGCAT", 1, -2, 2, 1);

**Comment by Dmitry-Antipov** [comment]
Sorry, 1,5 ,5,2 -- I've used the wrapper same to your example from readme file

**Comment by lh3** [comment]
Z-drop may detect out-of-band, but doesn't always work. It may also drop alignments you want to keep. The better way is to check if CIGAR is close to the band boundary.

By the way, whether you can have insertions followed by deletions is determined by the scoring. This is not "nonsense".

**Comment by Dmitry-Antipov** [comment]
I still miss something. I was talking not about z-drop optimization (it was switched off), but about zdropped flag
In particular it's set to 1 here, and this place really looks like band's boundary, isn't it? https://github.com/lh3/ksw2/blob/4e0a1ccba8c6ccc87e0342c9712531bde783bf90/ksw2_extz2_sse.c#L112

**Comment by lh3** [comment]
That happens when the end position is not in the band, which means you can't find an alignment. It doesn't protect against general out-of-band cases.

**Comment by Dmitry-Antipov** [comment]
I see. Thank you!
