### ISSUE TITLE
Readme toy example missing initialization

### ISSUE THREAD

**Issue by fenderglass** [lh3/ksw2#6]
Hi,

I was experimenting with KSW2 library and started with the Readme example. However, it gives me a segfault on my machine (Linux x86_64, GCC 5.4.0). It seems that there is a missing initialization string (which exists in more complete `cli.c` example). If I add:

`memset(&ez, 0, sizeof(ksw_extz_t));`

after 11 line, everything works as expected.

Best,
Mikhail

**Comment by lh3** [comment]
Fixed via 89cdcb7. Thanks!
