### ISSUE TITLE
Making a distributable binary with ksw2

### ISSUE THREAD

**Issue by rob-p** [lh3/ksw2#7]
Hi @lh3,

  Thanks again for the great library!  I'm planning to make use of ksw2 to perform some on-demand alignment in a couple of projects.  I've made a simple [C++-wrapper](https://github.com/rob-p/ksw2), which seems to work well so far in practice.  However, one issue I'm concerned about is how ksw2 should be compiled.  Specifically, I would like to make use of the most advanced instruction set available on the target machine.  Is the only way to do this by compiling different versions of my binary (e.g., one that uses only SSE2 instructions, another that uses SSE4 etc.)?  How do you handle this issue when building a binary (e.g., via Bioconda) for minimap2?

Thanks!
Rob

**Comment by lh3** [comment]
You may read the [minimap2's Makefile](https://github.com/lh3/minimap2/blob/master/Makefile) and [ksw2_dispatch.c](https://github.com/lh3/minimap2/blob/master/ksw2_dispatch.c). The basic idea is that you compile different versions of the same algorithm, requiring different SIMD instruction sets, and then dynamically choose which version to use based on users' CPU. Intel developers call this strategy as "CPU dispatch". [This blog post](https://attractivechaos.wordpress.com/2017/09/04/on-cpu-dispatch/) gives a bit more information.

**Comment by rob-p** [comment]
Brilliant; this is exactly what I was looking for.  Thanks @lh3!
